language: php

php:
  - 5.6
  - 7.0
  - hhvm

script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - git clone -b master https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
  - php phpcs.phar --config-set installed_paths wpcs
  - php phpcs.phar --ignore=vendor,wpcs --standard=WordPress-Core .
