language: php

php:
  - 5.6
  - 7.0
  - hhvm

script:
  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
  - git clone -b master https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
  - php phpcs/bin/phpcs --config-set installed_paths wpcs
  - php phpcs/bin/phpcs --ignore=vendor,wpcs,phpcs --standard=WordPress-Core .
