language: php

php:
  - 5.6
  - 7.0

script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - git clone -b master https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
  - phpcs --config-set installed_paths wpcs
  - phpcs --ignore=vendor,wpcs --standard=WordPress-Core .
